repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-lint
      - id: go-imports
      - id: go-cyclo
      - id: validate-toml
      - id: golangci-lint
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy