exclude: ^(/workspaces/proteus/test)


repos:
  - repo: local
    hooks:
      - id: local-go-build
        name: Go Build
        entry: ./hooks/run-go-build.sh
        language: script

      - id: local-go-lint
        name: Go Lint
        entry: ./hooks/run-go-lint.sh
        language: script

      - id: local-go-test
        name: Go Test
        entry: ./hooks/run-go-test.sh
        language: script
